// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/device/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/device/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/device/[id].put').default>>>>
    }
    '/api/device': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/device/index.post').default>>>>
    }
    '/api/devices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/location/history/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/location/history/[userId].get').default>>>>
    }
    '/api/location': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/location/index.post').default>>>>
    }
    '/api/location/latest/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/location/latest/[userId].get').default>>>>
    }
    '/api/session/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/[id].get').default>>>>
    }
    '/api/session/:id/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/[id]/stop.post').default>>>>
    }
    '/api/session/active': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/active.get').default>>>>
    }
    '/api/session/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/start.post').default>>>>
    }
    '/api/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}